/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "RomanNum_TEST.check" instead.
 */

#include <check.h>

#line 1 "RomanNum_TEST.check"
#include "RomanNum.h"
#include<string.h>

int match;

START_TEST(WhenSingleRomanNumIsPassedACharReturnThatChar)
{
#line 7
	match = strcmp(RomanNum("I"),"I");	
	fail_unless(match == 0, "When RomanNum is passed a char it does not returns a char");

}
END_TEST

START_TEST(WhenMultiRomanNumIsPassedTheyAreReturned)
{
#line 11
	match = strcmp(RomanNum("XVI"),"XVI");	
	fail_unless(match == 0, "When RomanNum is passed a char it does not returns a char");

}
END_TEST

START_TEST(TestForCorrectInputFormat)
{
#line 15
	match = strcmp(RomanNum("MMMCMXCIXII"),"MMMCMXCIXII");
	fail_unless(match != 0, "Testing for correct formatting, MMMCMXCIXII is not a valid input due to the two 'I's after the X");

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, WhenSingleRomanNumIsPassedACharReturnThatChar);
    tcase_add_test(tc1_1, WhenMultiRomanNumIsPassedTheyAreReturned);
    tcase_add_test(tc1_1, TestForCorrectInputFormat);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
